export const artistas = [
  {
    slug: "los-tormentos",
    nombre: "Los Tormentos",
    genero: "Punk / Hardcore",
    ciudad: "Buenos Aires",
    bio: "Formados en 2015 en el conurbano bonaerense. Tres discos, cientos de shows en sótanos y un sonido que no pide permiso.",
    integrantes: ["Rulo — voz / guitarra", "Nati — bajo", "Facu — batería"],
    proximaFecha: "25 de abril — Club Cultural Matienzo",
  },
  {
    slug: "vortex-negro",
    nombre: "Vórtex Negro",
    genero: "Metal / Sludge",
    ciudad: "Córdoba",
    bio: "Riffs pesados, tempos lentos y distorsión máxima. Vórtex Negro lleva diez años aplastando escenarios del interior.",
    integrantes: ["Damián — voz / guitarra", "Caro — guitarra", "Topo — bajo", "Sergio — batería"],
    proximaFecha: "3 de mayo — La Sala del Horror",
  },
  {
    slug: "la-grieta",
    nombre: "La Grieta",
    genero: "Post-punk / Noise",
    ciudad: "Rosario",
    bio: "Post-punk oscuro con influencias del noise rock y la new wave. Su último EP fue grabado en vivo en una fábrica abandonada.",
    integrantes: ["Vera — voz / teclados", "Nico — guitarra", "Lu — bajo / coros"],
    proximaFecha: "10 de mayo — El Galpón de la Música",
  },
  {
    slug: "electrochoque",
    nombre: "Electrochoque",
    genero: "Industrial / EBM",
    ciudad: "Buenos Aires",
    bio: "Electrónica de cuerpo presente. Máquinas, sintetizadores analógicos y performances que desafían el límite entre música y ruido.",
    integrantes: ["Axel — producción / voz", "Sil — sintetizadores"],
    proximaFecha: "17 de mayo — Crobar",
  },
  {
    slug: "ruido-blanco",
    nombre: "Ruido Blanco",
    genero: "Ambient / Drone",
    ciudad: "Mendoza",
    bio: "Paisajes sonoros que se despliegan lentamente. Ruido Blanco propone una experiencia de escucha activa e inmersiva.",
    integrantes: ["Matías — guitarras / efectos", "Paula — electrónica / field recordings"],
    proximaFecha: "Próximamente",
  },
];

export const fechas = [
  {
    id: 1,
    artista: "Los Tormentos",
    fecha: "2026-04-25",
    lugar: "Club Cultural Matienzo",
    ciudad: "Buenos Aires",
    precio: "$3.500",
  },
  {
    id: 2,
    artista: "Vórtex Negro",
    fecha: "2026-05-03",
    lugar: "La Sala del Horror",
    ciudad: "Córdoba",
    precio: "$4.000",
  },
  {
    id: 3,
    artista: "La Grieta",
    fecha: "2026-05-10",
    lugar: "El Galpón de la Música",
    ciudad: "Rosario",
    precio: "$3.000",
  },
  {
    id: 4,
    artista: "Electrochoque",
    fecha: "2026-05-17",
    lugar: "Crobar",
    ciudad: "Buenos Aires",
    precio: "$5.000",
  },
];
